var O=window.O||{};
(function(a,h){function l(c){c==h&&(c=!k);c?a("#more-menu").addClass("show"):a("#more-menu").removeClass("show");k=c}function m(c){var g=a("#"+c+"-selector"),e=g.parent().parent();e.find(".tab-page.active").trigger("tabpagehide");e.find(".selector a.active, .tab-page.active").removeClass("active");g.addClass("active");e.find("#"+c).addClass("active").trigger("tabpageshow")}var d=window.O;a(document).ready(function(){a("#loader").hide()});d.init=function(a){d.navigation.serverBase=a;localStorage.getItem("sessionId")?
d.navigation.changePage("/activity/index"):d.navigation.changePage("/user/login")};var k=!1;a(document).on("click","#more-menu",function(){l(!1)});document.addEventListener("menubutton",function(){d.navigation.isLoading()||l();return!1},!1);a(document).on("click","#tab-item-4",function(){l(!0);return!1});document.addEventListener("backbutton",function(a){k?l(!1):d.navigation.back();a.preventDefault()},!1);d.handleFormError=function(c,g){a(".errorMessage").hide();for(var e in g){var d=a('[name="'+
(c+"["+e+"]")+'"]').parent();0<d.length&&d.each(function(c,b){var f=a(b).find(".errorMessage");0==f.length&&(f=a('<div class="errorMessage"></div>'),a(b).append(f));f.html(g[e].join("<br />")).show()})}};a(document).on("click","#flash-container",function(){a(this).hide()});var p=null;a(document.body).on("pagechange",function(){p&&clearTimeout(p);p=setTimeout(function(){a("#flash-container").hide()},3E3)});a(document).on("click",".tab-view .selector a",function(c){var d=a(c.currentTarget);m(d.attr("href").substr(1));
history.replaceState({},document.title,"#tab="+d.attr("href").substr(1));c.preventDefault()});a(document.body).on("pagechange",function(a){(a=location.hash)&&0<a.indexOf("tab=")&&m(a.match(/tab=([^&]+)/)[1])});a(document).on("click",".table-view-check li",function(c){c=a(this).find("input[type=checkbox]");c.prop("checked",!c.prop("checked"))});a(document).on("click",".profile-header .photo",function(){a("#Photo_file").click()});a(document).on("change","#Photo_file",function(){a("#photo-upload-form").submit()})})(jQuery);(function(a,h){function l(q,b,f){f=f||{};e=a.ajax({url:c.navigation.serverBase+q,context:document.body,data:b,type:b?"POST":"GET",processData:!(b instanceof FormData),contentType:b instanceof FormData?!1:"application/x-www-form-urlencoded",timeout:45E3,xhrFields:{withCredentials:!0},beforeSend:function(a){},error:function(b,c,f){console.error({e:f,s:c,x:b});b.cancel||alert(f||c);a("#loader").hide();e=h},success:function(b,c,d){0<d.getResponseHeader("Content-type").indexOf("javascript")?eval(b):m(q,
b,!0,f);a("#loader").hide();e=h}})}function m(a,b,c,d){d=b.indexOf("\x3c!--page:");if(0<=d){d+=9;d=JSON.parse(b.substr(d,b.indexOf("--\x3e")-d));document.title=d.title;var e=a.match(/return=([^&]+)/);n=e&&1<e.length?decodeURIComponent(e[1]):d.backUrl;a.match(/#.*/);c&&!d.disableCache&&localStorage.setItem(k(a),b);g.attr("id","page-"+d.id)}g.html(b);g.trigger("pagechange")}function d(c,b){b=b||{};e&&(e.cancel=!0,e.abort());if(!1!==g.trigger("pagebeforechange")){a("#loader").attr("class","").show();
var d=!0;if(!b.disableCache&&!b.data){var h=localStorage.getItem(k(c));h&&(m(c,h,!1),a("#flash-container").hide(),(d=!0!=b.cacheOnly)&&a("#loader").attr("class","mini").show())}d&&l(c,b.data,b)}}function k(a){return"cache:"+a.match(/[^#]+/)[0]}function p(c){var b=a(this),f=b.attr("action")||location.href,e=(b.attr("method")||"get").toLowerCase(),b="multipart/form-data"==b.attr("enctype")?new FormData(b[0]):b.serialize();"post"==e?d(f,{data:b}):d(f+(0<=f.indexOf("?")?"&":"?")+b);c.preventDefault()}
var c=window.O;c.navigation=c.navigation||{};var g=a(document.body),e=h,n=h;c.navigation.serverBase="";a.support.cors=!0;c.navigation.changePage=d;c.navigation.clearCache=function(a){if(a)localStorage.removeItem(k(a));else{a=localStorage.length;for(var b=0;b<a;b++){var c=localStorage.key(b);"cache:"==c.substr(0,6)&&localStorage.removeItem(c)}}};c.navigation.back=function(){if(n)return d(n),!0;navigator.app&&navigator.app.exitApp&&navigator.app.exitApp();return!1};c.navigation.isLoading=function(){return e!=
h};c.navigation.cancel=function(){return e?(e.cancel=!0,e.abort(),truel):!1};a(document).on("click","a",function(e){var b=this.getAttribute("href"),f=a(this);b&&"#"!=b[0]&&(f.hasClass("btn-post")?(b=f.attr("data-ask"),e.preventDefault(),b&&!confirm(b)||d(this.href,{data:f.attr("data-post")})):f.hasClass("btn-back")?(n||(n=b),c.navigation.back()):d(b),e.preventDefault())});g.on("pagechange",function(){g.find("form").submit(p)});a(document).ready(function(){a(document.body).trigger("pagechange")})})(jQuery);
//# sourceMappingURL=app.js.map
