var O=window.O||{};
(function(a,h){function l(d){d==h&&(d=!k);d?a("#more-menu").addClass("show"):a("#more-menu").removeClass("show");k=d}function n(d){var b=a("#"+d+"-selector"),e=b.parent().parent();e.find(".tab-page.active").trigger("tabpagehide");e.find(".selector a.active, .tab-page.active").removeClass("active");b.addClass("active");e.find("#"+d).addClass("active").trigger("tabpageshow")}var b=window.O;a(document).ready(function(){a("#loader").hide()});b.init=function(a){b.navigation.serverBase=a;(a=b.navigation.getCurrentPage())?
b.navigation.changePage(a):b.navigation.changePage("/site/boot?v="+b.clientVersion)};var k=!1;a(document).on("click","#more-menu",function(){l(!1)});document.addEventListener("menubutton",function(){b.navigation.isLoading()||l();return!1},!1);a(document).on("click","#tab-item-4",function(){l(!0);return!1});document.addEventListener("backbutton",function(a){k?l(!1):b.navigation.back();a.preventDefault()},!1);b.handleFormError=function(d,b){a(".errorMessage").hide();for(var e in b){var f=a('[name="'+
(d+"["+e+"]")+'"]').parent();0<f.length&&f.each(function(d,c){var g=a(c).find(".errorMessage");0==g.length&&(g=a('<div class="errorMessage"></div>'),a(c).append(g));g.html(b[e].join("<br />")).show()})}};a(document).on("click","#flash-container",function(){a(this).hide()});var p=null;a(document.body).on("pagechange",function(){p&&clearTimeout(p);p=setTimeout(function(){a("#flash-container").hide()},3E3)});a(document).on("click",".tab-view .selector a",function(d){var b=a(d.currentTarget);n(b.attr("href").substr(1));
history.replaceState({},document.title,"#tab="+b.attr("href").substr(1));d.preventDefault()});a(document.body).on("pagechange",function(a){(a=location.hash)&&0<a.indexOf("tab=")&&n(a.match(/tab=([^&]+)/)[1])});a(document).on("click",".table-view-check li",function(d){d=a(this).find("input[type=checkbox]");d.prop("checked",!d.prop("checked"))});a(document).on("click",".profile-header .photo",function(){a("#Photo_file").click()});a(document).on("change","#Photo_file",function(){a("#photo-upload-form").submit()})})(jQuery);(function(a,h){function l(b,c,g){g=g||{};e=a.ajax({url:d.navigation.serverBase+b,context:document.body,data:c,type:c?"POST":"GET",processData:!(c instanceof FormData),contentType:c instanceof FormData?!1:"application/x-www-form-urlencoded",timeout:45E3,xhrFields:{withCredentials:!0},beforeSend:function(a){},error:function(c,d,b){console.error({e:b,s:d,x:c});c.cancel||alert(b||d);a("#loader").hide();e=h},success:function(c,d,f){0<f.getResponseHeader("Content-type").indexOf("javascript")?eval(c):n(b,
c,!0,g);a("#loader").hide();e=h}})}function n(a,c,d,b){b=c.indexOf("\x3c!--page:");if(0<=b){b+=9;b=JSON.parse(c.substr(b,c.indexOf("--\x3e")-b));document.title=b.title;var e=a.match(/return=([^&]+)/);f=e&&1<e.length?decodeURIComponent(e[1]):b.backUrl;a.match(/#.*/);d&&!b.disableCache&&localStorage.setItem(k(a),c);sessionStorage.setItem("currentUrl",b.url);m.attr("id","page-"+b.id)}m.html(c);m.trigger("pagechange")}function b(b,c){c=c||{};e&&(e.cancel=!0,e.abort());if(!1!==m.trigger("pagebeforechange")){var d=
a("#loader").attr("class","").show(),f=!0;if(!c.disableCache&&!c.data){var h=localStorage.getItem(k(b));h&&(n(b,h,!1),a("#flash-container").hide(),(f=!0!=c.cacheOnly)&&d.attr("class","mini").show())}f&&l(b,c.data,c)}}function k(a){return"cache:"+a.match(/[^#]+/)[0]}function p(d){var c=a(this),e=c.attr("action")||location.href,f=(c.attr("method")||"get").toLowerCase(),c="multipart/form-data"==c.attr("enctype")?new FormData(c[0]):c.serialize();"post"==f?b(e,{data:c}):b(e+(0<=e.indexOf("?")?"&":"?")+
c);d.preventDefault()}var d=window.O;d.navigation=d.navigation||{};var m=a(document.body),e=h,f=h;d.navigation.serverBase="";a.support.cors=!0;d.navigation.changePage=b;d.navigation.getCurrentPage=function(){return sessionStorage.getItem("currentUrl")||null};d.navigation.clearCache=function(a){if(a)localStorage.removeItem(k(a));else{a=localStorage.length;for(var b=0;b<a;b++){var d=localStorage.key(b);"cache:"==d.substr(0,6)&&localStorage.removeItem(d)}}};d.navigation.back=function(){if(f)return b(f),
!0;navigator.app&&navigator.app.exitApp&&navigator.app.exitApp();return!1};d.navigation.isLoading=function(){return e!=h};d.navigation.cancel=function(){return e?(e.cancel=!0,e.abort(),truel):!1};a(document).on("click","a",function(e){var c=this.getAttribute("href"),g=a(this);c&&"#"!=c[0]&&(g.hasClass("btn-post")?(c=g.attr("data-ask"),e.preventDefault(),c&&!confirm(c)||b(this.href,{data:g.attr("data-post")})):g.hasClass("btn-back")?(f||(f=c),d.navigation.back()):b(c),e.preventDefault())});m.on("pagechange",
function(){m.find("form").submit(p)});a(document).ready(function(){a(document.body).trigger("pagechange")})})(jQuery);
//# sourceMappingURL=app.js.map
