var O=window.O||{};
(function(a,g){function k(d){d==g&&(d=!h);d?a("#more-menu").addClass("show"):a("#more-menu").removeClass("show");h=d}function l(d){var f=a("#"+d+"-selector"),e=f.parent().parent();e.find(".tab-page.active").trigger("tabpagehide");e.find(".selector a.active, .tab-page.active").removeClass("active");f.addClass("active");e.find("#"+d).addClass("active").trigger("tabpageshow")}var c=window.O;a(document).ready(function(){a("#loader").hide()});c.init=function(a){c.navigation.serverBase=a;localStorage.getItem("sessionId")?
c.navigation.changePage("/activity/index"):c.navigation.changePage("/user/login")};var h=!1;a(document).on("click","#more-menu",function(){k(!1)});document.addEventListener("menubutton",function(){c.navigation.isLoading()||k();return!1},!1);a(document).on("click","#tab-item-4",function(){k(!0);return!1});document.addEventListener("backbutton",function(a){h?k(!1):c.navigation.back();a.preventDefault()},!1);c.handleFormError=function(d,f){a(".errorMessage").hide();for(var e in f){var c=a('[name="'+
(d+"["+e+"]")+'"]').parent();0<c.length&&c.forEach(function(d){var b=a(d).find(".errorMessage");0==b.length&&(b=a('<div class="errorMessage"></div>'),a(d).append(b));b.html(f[e].join("<br />")).show()})}};a(document).on("click","#flash-container",function(){a(this).hide()});var n=null;a(document.body).on("pagechange",function(){n&&clearTimeout(n);n=setTimeout(function(){a("#flash-container").hide()},3E3)});a(document).on("click",".tab-view .selector a",function(d){var c=a(d.currentTarget);l(c.attr("href").substr(1));
history.replaceState({},document.title,"#tab="+c.attr("href").substr(1));d.preventDefault()});a(document.body).on("pagechange",function(a){(a=location.hash)&&0<a.indexOf("tab=")&&l(a.match(/tab=([^&]+)/)[1])});a(document).on("click",".table-view-check li",function(d){d=a(this).find("input[type=checkbox]");d.prop("checked",!d.prop("checked"))});a(document).on("click",".profile-header .photo",function(){a("#Photo_file").click()});a(document).on("change","#Photo_file",function(){a("#photo-upload-form").submit()})})(jQuery);(function(a,g){function k(p,b,c){c=c||{};e=a.ajax({url:d.navigation.serverBase+p,context:document.body,data:b,type:b?"POST":"GET",processData:!(b instanceof FormData),contentType:b instanceof FormData?!1:"application/x-www-form-urlencoded",timeout:45E3,xhrFields:{withCredentials:!0},beforeSend:function(a){},error:function(b,d,c){console.error({e:c,s:d,x:b});b.cancel||alert(c||d);a("#loader").hide();e=g},success:function(b,d,f){0<f.getResponseHeader("Content-type").indexOf("javascript")?eval(b):l(p,
b,!0,c);a("#loader").hide();e=g}})}function l(a,b,d,c){c=b.indexOf("\x3c!--page:");if(0<=c){c+=9;c=JSON.parse(b.substr(c,b.indexOf("--\x3e")-c));document.title=c.title;var e=a.match(/return=([^&]+)/);m=e&&1<e.length?decodeURIComponent(e[1]):c.backUrl;a.match(/#.*/);d&&!c.disableCache&&localStorage.setItem(h(a),b);f.attr("id","page-"+c.id)}f.html(b);f.trigger("pagechange")}function c(c,b){b=b||{};e&&(e.cancel=!0,e.abort());if(!1!==f.trigger("pagebeforechange")){a("#loader").attr("class","").show();
var d=!0;if(!b.disableCache&&!b.data){var g=localStorage.getItem(h(c));g&&(l(c,g,!1),a("#flash-container").hide(),(d=!0!=b.cacheOnly)&&a("#loader").attr("class","mini").show())}d&&k(c,b.data,b)}}function h(a){return"cache:"+a.match(/[^#]+/)[0]}function n(d){var b=a(this),e=b.attr("action")||location.href,f=(b.attr("method")||"get").toLowerCase(),b="multipart/form-data"==b.attr("enctype")?new FormData(b[0]):b.serialize();"post"==f?c(e,{data:b}):c(e+(0<=e.indexOf("?")?"&":"?")+b);d.preventDefault()}
var d=window.O;d.navigation=d.navigation||{};var f=a(document.body),e=g,m=g;d.navigation.serverBase="";a.support.cors=!0;d.navigation.changePage=c;d.navigation.clearCache=function(a){if(a)localStorage.removeItem(h(a));else{a=localStorage.length;for(var b=0;b<a;b++){var c=localStorage.key(b);"cache:"==c.substr(0,6)&&localStorage.removeItem(c)}}};d.navigation.back=function(){if(m)return c(m,{cacheOnly:!0}),!0;navigator.app&&navigator.app.exitApp&&navigator.app.exitApp();return!1};d.navigation.isLoading=
function(){return e!=g};d.navigation.cancel=function(){return e?(e.cancel=!0,e.abort(),truel):!1};a(document).on("click","a",function(e){var b=this.getAttribute("href"),f=a(this);b&&"#"!=b[0]&&(f.hasClass("btn-post")?(b=f.attr("data-ask"),e.preventDefault(),b&&!confirm(b)||c(this.href,{data:f.attr("data-post")})):f.hasClass("btn-back")?(m||(m=b),d.navigation.back()):c(b),e.preventDefault())});f.on("pagechange",function(){f.find("form").submit(n)});a(document).ready(function(){a(document.body).trigger("pagechange")})})(jQuery);
